import re

with open("src/content/concepts/claude-designer-stack.js", "r") as f:
    content = f.read()

# Remove the figma-ui-kit paragraph
content = re.sub(r'<p style="margin-bottom: 1rem; line-height: 1.75;">The <code style="padding: 0.15rem 0.35rem; background: var\(--syntax-bg\); border-radius: 4px; color: var\(--accent-primary\);">figma-ui-kit</code> skill is currently a custom/internal skill and must be added locally to your <code style="padding: 0.15rem 0.35rem; background: var\(--syntax-bg\); border-radius: 4px; color: var\(--accent-primary\);">.claude/skills/</code> directory.</p>\n', '', content)

# Remove the figma-ui-kit block
block_to_remove = """    },
    {
      label: '2. figma-ui-kit',
      content: `
<h2 style="margin-bottom: 1rem; color: var(--text-primary);">2. figma-ui-kit</h2>

<p style="margin-bottom: 1rem; line-height: 1.75;"><strong>What it does:</strong> Generates fully styled, production-ready React / Tailwind components designed to be exact replicas of items generated by Anthropic's official Claude UI Kit Figma file.</p>

<p style="margin-bottom: 1rem; line-height: 1.75;"><strong>How to call it:</strong> Try asking it to recreate specific screens from the UI Kit, or to mix and match elements.</p>

<p style="margin-bottom: 0.5rem; line-height: 1.75;"><strong>Example prompts:</strong></p>
<pre style="display: block; padding: 0.9rem 1rem; background: var(--syntax-bg); border: 1px solid var(--border-color); border-radius: 8px; margin: 0.5rem 0; font-family: 'JetBrains Mono', monospace; color: var(--syntax-text); white-space: pre-wrap; font-size: 0.9rem; line-height: 1.6;">"I need a dashboard view based on the Claude UI Kit. Include a sidebar, a top nav, and a grid of cards."</pre>
<pre style="display: block; padding: 0.9rem 1rem; background: var(--syntax-bg); border: 1px solid var(--border-color); border-radius: 8px; margin: 0.5rem 0; font-family: 'JetBrains Mono', monospace; color: var(--syntax-text); white-space: pre-wrap; font-size: 0.9rem; line-height: 1.6;">"Generate a settings page that uses the typography and colors from the figma-ui-kit."</pre>
<pre style="display: block; padding: 0.9rem 1rem; background: var(--syntax-bg); border: 1px solid var(--border-color); border-radius: 8px; margin: 0.5rem 0 1rem; font-family: 'JetBrains Mono', monospace; color: var(--syntax-text); white-space: pre-wrap; font-size: 0.9rem; line-height: 1.6;">"Build a modal component mimicking the Dialog in the Claude UI kit, with a dark backdrop."</pre>
`,"""
content = content.replace(block_to_remove, "")

# Shift numbering down
content = content.replace("3. theme-factory", "2. theme-factory")
content = content.replace("4. brand-guidelines", "3. brand-guidelines")
content = content.replace("5. canvas-design", "4. canvas-design")
content = content.replace("6. skill-creator", "5. skill-creator")
content = content.replace("Combine All 6", "Combine All 5")
content = content.replace("A 6-Skill Pipeline", "A 5-Skill Pipeline")

# Phase section removals
phase_4_to_remove = """<hr style="border: 0; border-top: 1px solid var(--border-color); margin: 1.5rem 0;">

<h3 style="margin-top: 1.5rem; margin-bottom: 0.75rem; color: var(--text-primary);">Phase 4 — Implement UI Kit Components (<code style="padding: 0.15rem 0.35rem; background: var(--syntax-bg); border-radius: 4px; color: var(--accent-primary);">figma-ui-kit</code>)</h3>

<p style="margin-bottom: 1rem; line-height: 1.75;">Your design calls for a consistent Prompt Card layout. Rather than building from scratch, use the UI Kit to pull in pre-designed, production-ready components.</p>

<p style="margin-bottom: 0.35rem; line-height: 1.75;"><strong>Prompt:</strong></p>
<pre style="display: block; padding: 0.9rem 1rem; background: var(--syntax-bg); border: 1px solid var(--border-color); border-radius: 8px; margin: 0.5rem 0 1rem; font-family: 'JetBrains Mono', monospace; color: var(--syntax-text); white-space: pre-wrap; font-size: 0.9rem; line-height: 1.6;">"Use the figma-ui-kit skill to generate a PromptCard component.
Include a specific hover state, tag pill styling, and a three-dot overflow menu.
Ensure it uses our existing CSS variables for typography and colors."</pre>

<p style="margin-bottom: 1rem; line-height: 1.75;">The <code style="padding: 0.15rem 0.35rem; background: var(--syntax-bg); border-radius: 4px; color: var(--accent-primary);">figma-ui-kit</code> skill reads the Anthropic UI Kit templates and generates the <code style="padding: 0.15rem 0.35rem; background: var(--syntax-bg); border-radius: 4px; color: var(--accent-primary);">PromptCard</code> component directly, matching the exact spacing and tokens expected.</p>

"""
content = content.replace(phase_4_to_remove, "")
content = content.replace("Phase 5", "Phase 4")
content = content.replace("Phase 6", "Phase 5")

# Remove from skill-creator list
content = content.replace("- Include a figma-ui-kit integration step for component-level fidelity\n", "")

# Remove from flow diagram
flow_diagram_old = """frontend-design   →  React 19 + Vite 8 app (MainLayout, Sidebar, Search, Cards)
      ↓
figma-ui-kit      →  Production-ready PromptCard from UI Kit
      ↓
brand-guidelines  →  Final brand consistency pass"""
flow_diagram_new = """frontend-design   →  React 19 + Vite 8 app (MainLayout, Sidebar, Search, Cards)
      ↓
brand-guidelines  →  Final brand consistency pass"""
content = content.replace(flow_diagram_old, flow_diagram_new)

# Remove artifact passing mention
content = content.replace("the theme feeds the frontend build, figma-ui-kit fills in component-level detail, brand-guidelines polishes", "the theme feeds the frontend build, brand-guidelines polishes")

# Remove table row
table_row_to_remove = """    <tr style="border-bottom: 1px solid var(--border-color);">
      <td style="padding: 0.75rem;"><code style="padding: 0.15rem 0.35rem; background: var(--syntax-bg); border-radius: 4px; color: var(--accent-primary);">figma-ui-kit</code></td>
      <td style="padding: 0.75rem;">"Claude UI Kit," "dashboard view," "settings page"</td>
      <td style="padding: 0.75rem;">"Use the figma-ui-kit skill to..."</td>
    </tr>\n"""
content = content.replace(table_row_to_remove, "")

# Remove Figma MCP docs from resources
content = re.sub(r'\s*<li><strong>Figma MCP Skills Docs:</strong>.*?figma-mcp-server.*?</li>', '', content)

with open("src/content/concepts/claude-designer-stack.js", "w") as f:
    f.write(content)

print("done")
